<?php
echo "Content-Type: text/html\r\n";
echo "Status: 418 I'm a teapot\r\n\r\n";

echo '<!DOCTYPE html>'."\n" ;
echo '<html>'."\n" ;
echo '<head>'."\n" ;
echo '<meta charset="UTF-8">'."\n" ;
echo '<title>~/Documents/webserv/Makefile.html</title>'."\n" ;
echo '<meta name="Generator" content="Vim/8.2">'."\n" ;
echo '<meta name="plugin-version" content="vim8.1_v2">'."\n" ;
echo '<meta name="syntax" content="make">'."\n" ;
echo '<meta name="settings" content="use_css,pre_wrap,no_foldcolumn,prevent_copy=,use_input_for_pc=fallback">'."\n" ;
echo '<meta name="colorscheme" content="none">'."\n" ;
echo '<style>'."\n" ;
echo '<!--'."\n" ;
echo 'pre { white-space: pre-wrap; font-family: monospace; color: #ffffff; background-color: #000000; }'."\n" ;
echo 'body { font-family: monospace; color: #ffffff; background-color: #000000; }'."\n" ;
echo '* { font-size: 1em; }'."\n" ;
echo '.Identifier { color: #00ffff; font-weight: bold; }'."\n" ;
echo '.PreProc { color: #5fd7ff; }'."\n" ;
echo '.Statement { color: #ffff00; }'."\n" ;
echo '.Comment { color: #00ffff; }'."\n" ;
echo '.Constant { color: #ff40ff; }'."\n" ;
echo '.Special { color: #ffd7d7; }'."\n" ;
echo '-->'."\n" ;
echo '</style>'."\n" ;
echo '</head>'."\n" ;
echo '<body>'."\n" ;
echo '<pre id=\'vimCodeElement\'>'."\n" ;
echo '<span class="Comment">### config</span>'."\n" ;
echo '<span class="Identifier">NAME		</span>= webserv'."\n" ;
echo '<span class="Identifier">CXX			</span>= c++'."\n" ;
echo '<span class="Identifier">CFLAGS		</span>= -std=c++98 -Wall -Werror -Wextra -g3'."\n" ;
echo '<span class="Identifier">DEPFLAGS	</span>= -MMD -MP'."\n" ;
echo '<span class="Identifier">OS          </span>= <span class="Identifier">$(</span><span class="Statement">shell</span><span class="Identifier"> uname)</span>'."\n" ;
echo ''."\n" ;
echo ''."\n" ;
echo '<span class="Comment">### program files</span>'."\n" ;
echo '<span class="Identifier">FILE_EXTENSION	</span>= .cpp'."\n" ;
echo '<span class="Identifier">SRCS_PATH		</span>= ./src'."\n" ;
echo '<span class="Identifier">INCLUDE_PATH	</span>= ./inc'."\n" ;
echo '<span class="Identifier">OBJ_PATH		</span>= ./.obj'."\n" ;
echo '<span class="Identifier">SRCS_FILES		</span>= main.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>Request.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>Response.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>Server.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>Atributes.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>Location.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>Parser.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>args.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>ConfigurationServer.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>utils/isSeparator.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>utils/strNoCase.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>utils/strIsdigit.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>utils/findInsensitive.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>utils/getExt.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>exceptions/LocationException.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>Redirection.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>Epoll.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>CGI.cpp <span class="Special">\</span>'."\n" ;
echo '<span class="Special">                  </span>addRedirect.cpp <span class="Special">\</span>'."\n" ;
echo ''."\n" ;
echo ''."\n" ;
echo '<span class="PreProc">ifeq</span> (<span class="Identifier">$(OS)</span>, Linux)'."\n" ;
echo '	CFLAGS += -DLINUX'."\n" ;
echo '<span class="PreProc">endif</span>'."\n" ;
echo ''."\n" ;
echo '<span class="Identifier">SRCS </span>= <span class="Identifier">$(</span><span class="Statement">addprefix</span><span class="Identifier"> $(SRCS_PATH)/, $(SRCS_FILES))</span>'."\n" ;
echo '<span class="Identifier">HEADERS			</span>= <span class="Identifier">$(</span><span class="Statement">wildcard</span><span class="Identifier"> $(INCLUDE_PATH)/*.hpp)</span>'."\n" ;
echo ''."\n" ;
echo '<span class="Comment">### objects definition</span>'."\n" ;
echo '<span class="Identifier">OBJS </span>= <span class="Identifier">$(</span><span class="Statement">patsubst</span><span class="Identifier"> $(SRCS_PATH)/%$(FILE_EXTENSION),$(OBJ_PATH)/%.o,$(SRCS))</span>'."\n" ;
echo '<span class="Identifier">DEPS </span>= <span class="Identifier">$(</span><span class="Statement">patsubst</span><span class="Identifier"> $(SRCS_PATH)/%$(FILE_EXTENSION),$(OBJ_PATH)/%.d,$(SRCS))</span>'."\n" ;
echo ''."\n" ;
echo '<span class="Comment">### Makefile rules</span>'."\n" ;
echo '<span class="Identifier">all:</span> <span class="Identifier">$(NAME)</span>'."\n" ;
echo '<span class="Special">	@</span><span class="Constant">mkdir -p static/uploads</span>'."\n" ;
echo ''."\n" ;
echo '<span class="Identifier">$(NAME):</span> <span class="Identifier">${OBJS}</span>'."\n" ;
echo '<span class="Constant">	</span><span class="Identifier">$(CXX)</span><span class="Constant"> </span><span class="Identifier">$(CFLAGS)</span><span class="Constant"> -o </span><span class="Identifier">$@</span><span class="Constant"> </span><span class="Identifier">${OBJS}</span>'."\n" ;
echo ''."\n" ;
echo '<span class="Identifier">$(OBJ_PATH)/%.o:</span> <span class="Identifier">$(SRCS_PATH)</span>/<span class="Identifier">%$(FILE_EXTENSION)</span> <span class="Identifier">$(HEADERS)</span> Makefile'."\n" ;
echo '<span class="Constant">	mkdir -p </span><span class="Identifier">$(</span><span class="Statement">dir</span><span class="Identifier"> $@)</span>'."\n" ;
echo '<span class="Constant">	</span><span class="Identifier">$(CXX)</span><span class="Constant"> </span><span class="Identifier">$(CFLAGS)</span><span class="Constant"> </span><span class="Identifier">$(DEPFLAGS)</span><span class="Constant"> -c </span><span class="Identifier">$&lt;</span><span class="Constant"> -o </span><span class="Identifier">$@</span><span class="Constant"> -I</span><span class="Identifier">$(INCLUDE_PATH)</span>'."\n" ;
echo ''."\n" ;
echo '<span class="Identifier">clean:</span>'."\n" ;
echo '<span class="Special">	@</span><span class="Constant">rm -fr </span><span class="Identifier">$(OBJ_PATH)</span>'."\n" ;
echo ''."\n" ;
echo '<span class="Identifier">fclean:</span> clean'."\n" ;
echo '<span class="Special">	@</span><span class="Constant">rm -rf static/uploads/*</span>'."\n" ;
echo '<span class="Special">	@</span><span class="Constant">rm -rf </span><span class="Identifier">$(NAME)</span>'."\n" ;
echo ''."\n" ;
echo '<span class="Identifier">debug:</span> fclean'."\n" ;
echo '<span class="Identifier">debug:</span> CFLAGS += -DDEBUG -g3'."\n" ;
echo '<span class="Identifier">debug:</span> all'."\n" ;
echo ''."\n" ;
echo '<span class="Identifier">re:</span> fclean'."\n" ;
echo '<span class="Special">	@</span><span class="Identifier">$(MAKE)</span><span class="Constant"> --no-print-directory all</span>'."\n" ;
echo ''."\n" ;
echo '<span class="PreProc">-include $(DEPS)</span>'."\n" ;
echo '<span class="Statement">.PHONY:</span> all clean fclean re'."\n" ;
echo '</pre>'."\n" ;
echo '</body>'."\n" ;
echo '</html>'."\n" ;
