
error_page  404 403 402 frfrfr;
server {
    limit_except GET PUT;
    listen 127.0.0.1 8080;
    server_name localhost;
    client_max_body_size    5000;
    error_page    403 /static/error/403.html;
    root /static;
    location /ed {
        rOOt /static;
        index index.html Client.hpp Makefile;
        error_page    404 /static/error/404.html;
        client_max_body_size    200;
        autoindex on;
    }
    location /static {
            root /static;
            index main.cpp Client.hpp Makefile;
            error_page    404 /static/error/404.html;
            client_max_body_size    200;
    }
    location /cgis {
        rOOt /static/CGI-scripts ;
        index main.cpp Client.hpp Makefile;
        cgi .py:/usr/bin/python3 .php:/usr/bin/php .js:/usr/bin/node;
        error_page    403 /static/error/403.html;
        client_max_body_size    20000000;
        autoindex on;
    }
}

server {
    limit_except GET PUT;

    listen 0.0.0.0 8080;
    client_max_body_size    5000;
    error_page    403 /static/error/403.html;
    root /static;
    location /edd {
        rOOt /static;
        index index.html Client.hpp Makefile;
        error_page    404 /static/error/404.html;
        client_max_body_size    200;
        autoindex on;
    }
    location /static {
            root /static;
            index main.cpp Client.hpp Makefile;
            error_page    404 /static/error/404.html;
            client_max_body_size    200;
    }
}