server {
	server_name localhost;
	listen 0.0.0.0 8080;
	cgi .bla /home/geymat/Downloads/ubuntu_cgi_tester;
	limit_except GET;
	autoindex on;
	root static/sgoinfre/talibert/webserv/tester/YoupiBanane;

	location / {
		limit_except GET;
	}

	location /put_test/ {
		limit_except PUT;
	}

	location /post_body {
		limit_except POST;
		client_max_body_size 100;
	}

	location /directory {
		limit_except GET POST;
		autoindex off;
		index youpi.bad_extension;
		client_max_body_size 1000000000000000;
	}

}
