

server {
	server_name localhost;
	listen 0.0.0.0 8080;
	cgi .bla ./ubuntu_cgi_tester;
	limit_except GET;
	autoindex on;
	location / {
		limit_except GET;
		root .//sgoinfre/talibert/webserv/tester;
	}

	location /put_test/ {
		limit_except PUT;
		root .;
		upload_folder ./sgoinfre/talibert/webserv/tester/uploads;
	}

	location /post_body {
		limit_except POST;
		client_max_body_size 100;
		root ./sgoinfre/talibert/webserv/tester;
	}

	location /directory {
		limit_except GET POST;
		autoindex off;
		root ./sgoinfre/talibert/webserv/tester/YoupiBanane;
		index youpi.bad_extension;
	}

}
