
#include "Response.hpp"

std::map<std::vector<std::string>, std::string> &Response::getExt()
{
    static std::map<std::vector<std::string>, std::string> extensions;
    if (!extensions.empty())
        return extensions;

    std::vector<std::string> vals;
    vals.push_back("html");
    vals.push_back("htm");
    vals.push_back("shtml");
    extensions[vals] = "text/html";
    vals.clear();
    vals.push_back("html");
    vals.push_back("htm");
    vals.push_back("shtml");
    extensions[vals] = "text/html";
    vals.clear();
    vals.push_back("css");
    extensions[vals] = "text/css";
    vals.clear();
    vals.push_back("xml");
    extensions[vals] = "text/xml";
    vals.clear();
    vals.push_back("gif");
    extensions[vals] = "image/gif";
    vals.clear();
    vals.push_back("jpeg");
    vals.push_back("jpg");
    extensions[vals] = "image/jpeg";
    vals.clear();
    vals.push_back("js");
    extensions[vals] = "application/javascript";
    vals.clear();
    vals.push_back("atom");
    extensions[vals] = "application/atom+xml";
    vals.clear();
    vals.push_back("rss");
    extensions[vals] = "application/rss+xml";
    vals.clear();
    vals.push_back("mml");
    extensions[vals] = "text/mathml";
    vals.clear();
    vals.push_back("txt");
    extensions[vals] = "text/plain";
    vals.clear();
    vals.push_back("jad");
    extensions[vals] = "text/vnd.sun.j2me.app-descriptor";
    vals.clear();
    vals.push_back("wml");
    extensions[vals] = "text/vnd.wap.wml";
    vals.clear();
    vals.push_back("htc");
    extensions[vals] = "text/x-component";
    vals.clear();
    vals.push_back("png");
    extensions[vals] = "image/png";
    vals.clear();
    vals.push_back("tif");
    vals.push_back("tiff");
    extensions[vals] = "image/tiff";
    vals.clear();
    vals.push_back("wbmp");
    extensions[vals] = "image/vnd.wap.wbmp";
    vals.clear();
    vals.push_back("ico");
    extensions[vals] = "image/x-icon";
    vals.clear();
    vals.push_back("jng");
    extensions[vals] = "image/x-jng";
    vals.clear();
    vals.push_back("bmp");
    extensions[vals] = "image/x-ms-bmp";
    vals.clear();
    vals.push_back("svg");
    vals.push_back("svgz");
    extensions[vals] = "image/svg+xml";
    vals.clear();
    vals.push_back("webp");
    extensions[vals] = "image/webp";
    vals.clear();
    vals.push_back("woff");
    extensions[vals] = "application/font-woff";
    vals.clear();
    vals.push_back("jar");
    vals.push_back("war");
    vals.push_back("ear");
    extensions[vals] = "application/java-archive";
    vals.clear();
    vals.push_back("json");
    extensions[vals] = "application/json";
    vals.clear();
    vals.push_back("hqx");
    extensions[vals] = "application/mac-binhex40";
    vals.clear();
    vals.push_back("doc");
    extensions[vals] = "application/msword";
    vals.clear();
    vals.push_back("pdf");
    extensions[vals] = "application/pdf";
    vals.clear();
    vals.push_back("ps");
    vals.push_back("eps");
    vals.push_back("ai");
    extensions[vals] = "application/postscript";
    vals.clear();
    vals.push_back("rtf");
    extensions[vals] = "application/rtf";
    vals.clear();
    vals.push_back("m3u8");
    extensions[vals] = "application/vnd.apple.mpegurl";
    vals.clear();
    vals.push_back("xls");
    extensions[vals] = "application/vnd.ms-excel";
    vals.clear();
    vals.push_back("eot");
    extensions[vals] = "application/vnd.ms-fontobject";
    vals.clear();
    vals.push_back("ppt");
    extensions[vals] = "application/vnd.ms-powerpoint";
    vals.clear();
    vals.push_back("wmlc");
    extensions[vals] = "application/vnd.wap.wmlc";
    vals.clear();
    vals.push_back("kml");
    extensions[vals] = "application/vnd.google-earth.kml+xml";
    vals.clear();
    vals.push_back("kmz");
    extensions[vals] = "application/vnd.google-earth.kmz";
    vals.clear();
    vals.push_back("7z");
    extensions[vals] = "application/x-7z-compressed";
    vals.clear();
    vals.push_back("cco");
    extensions[vals] = "application/x-cocoa";
    vals.clear();
    vals.push_back("jardiff");
    extensions[vals] = "application/x-java-archive-diff";
    vals.clear();
    vals.push_back("jnlp");
    extensions[vals] = "application/x-java-jnlp-file";
    vals.clear();
    vals.push_back("run");
    extensions[vals] = "application/x-makeself";
    vals.clear();
    vals.push_back("pl");
    vals.push_back("pm");
    extensions[vals] = "application/x-perl";
    vals.clear();
    vals.push_back("prc");
    vals.push_back("pdb");
    extensions[vals] = "application/x-pilot";
    vals.clear();
    vals.push_back("rar");
    extensions[vals] = "application/x-rar-compressed";
    vals.clear();
    vals.push_back("rpm");
    extensions[vals] = "application/x-redhat-package-manager";
    vals.clear();
    vals.push_back("sea");
    extensions[vals] = "application/x-sea";
    vals.clear();
    vals.push_back("swf");
    extensions[vals] = "application/x-shockwave-flash";
    vals.clear();
    vals.push_back("sit");
    extensions[vals] = "application/x-stuffit";
    vals.clear();
    vals.push_back("tcl");
    vals.push_back("tk");
    extensions[vals] = "application/x-tcl";
    vals.clear();
    vals.push_back("der");
    vals.push_back("pem");
    vals.push_back("crt");
    extensions[vals] = "application/x-x509-ca-cert";
    vals.clear();
    vals.push_back("xpi");
    extensions[vals] = "application/x-xpinstall";
    vals.clear();
    vals.push_back("xhtml");
    extensions[vals] = "application/xhtml+xml";
    vals.clear();
    vals.push_back("xspf");
    extensions[vals] = "application/xspf+xml";
    vals.clear();
    vals.push_back("zip");
    extensions[vals] = "application/zip";
    vals.clear();
    vals.push_back("bin");
    vals.push_back("exe");
    vals.push_back("dll");
    extensions[vals] = "application/octet-stream";
    vals.clear();
    vals.push_back("deb");
    extensions[vals] = "application/octet-stream";
    vals.clear();
    vals.push_back("dmg");
    extensions[vals] = "application/octet-stream";
    vals.clear();
    vals.push_back("iso");
    vals.push_back("img");
    extensions[vals] = "application/octet-stream";
    vals.clear();
    vals.push_back("msi");
    vals.push_back("msp");
    vals.push_back("msm");
    extensions[vals] = "application/octet-stream";
    vals.clear();
    vals.push_back("docx");
    extensions[vals] = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    vals.clear();
    vals.push_back("xlsx");
    extensions[vals] = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    vals.clear();
    vals.push_back("pptx");
    extensions[vals] = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
    vals.clear();
    vals.push_back("mid");
    vals.push_back("midi");
    vals.push_back("kar");
    extensions[vals] = "audio/midi";
    vals.clear();
    vals.push_back("mp3");
    extensions[vals] = "audio/mpeg";
    vals.clear();
    vals.push_back("ogg");
    extensions[vals] = "audio/ogg";
    vals.clear();
    vals.push_back("m4a");
    extensions[vals] = "audio/x-m4a";
    vals.clear();
    vals.push_back("ra");
    extensions[vals] = "audio/x-realaudio";
    vals.clear();
    vals.push_back("3gpp");
    vals.push_back("3gp");
    extensions[vals] = "video/3gpp";
    vals.clear();
    vals.push_back("ts");
    extensions[vals] = "video/mp2t";
    vals.clear();
    vals.push_back("mp4");
    extensions[vals] = "video/mp4";
    vals.clear();
    vals.push_back("mpeg");
    vals.push_back("mpg");
    extensions[vals] = "video/mpeg";
    vals.clear();
    vals.push_back("mov");
    extensions[vals] = "video/quicktime";
    vals.clear();
    vals.push_back("webm");
    extensions[vals] = "video/webm";
    vals.clear();
    vals.push_back("flv");
    extensions[vals] = "video/x-flv";
    vals.clear();
    vals.push_back("m4v");
    extensions[vals] = "video/x-m4v";
    vals.clear();
    vals.push_back("mng");
    extensions[vals] = "video/x-mng";
    vals.clear();
    vals.push_back("asx");
    vals.push_back("asf");
    extensions[vals] = "video/x-ms-asf";
    vals.clear();
    vals.push_back("wmv");
    extensions[vals] = "video/x-ms-wmv";
    vals.clear();
    vals.push_back("avi");
    extensions[vals] = "video/x-msvideo";
    vals.clear();
    return extensions;
}